/**
 * Templates for research project agent workspace files.
 * Generated by `openclaw research init <id>` CLI command.
 */

export function renderBootstrapMd(projectName: string): string {
  return `# Research Agent Bootstrap

You were just created as the research agent for project "${projectName}". Complete the initial setup before starting downstream work.

## Bootstrap Flow

1. Greet the user, explain that you are the research agent for project "${projectName}", and ask them to describe the research direction.
2. Based on the user's answer, extract:
   - core-domain keywords (3-5)
   - suggested arXiv categories (for example "cs.LG", "cs.AI"); leave empty if the topic is outside arXiv coverage
   - preferred literature sources ("arxiv", "openalex", or both)
3. Discuss scope and priorities with the user, confirm the configuration, and accept adjustments.
4. Once confirmed, write the following files:
   - update SOUL.md with the project direction and domain fields
   - generate config.json using the template below
5. Ask whether the user wants to run Day 0 immediately to build the initial knowledge state.
   - If yes, run /metabolism to perform the first literature retrieval and knowledge-base construction pass.
6. If the project already has partial outputs, use the shortest matching path instead of restarting from Day 0:
   - existing papers/ -> /research-survey
   - existing survey_res.md, but route still undecided -> /algorithm-selection
   - existing survey_res.md -> /research-plan
   - existing plan_res.md, and metric definitions or evidence layers still look unclear -> /metric-audit
   - existing plan_res.md, but data quality still needs review -> /dataset-validate
   - existing plan_res.md, and the project needs a decisive component-level validation plan -> /ablation-planner
   - existing plan_res.md, and matched baseline evidence is needed -> /baseline-runner
   - multiple runs or configs already exist, but the registry is still messy -> /experiment-tracker
   - existing implementation code -> /research-review
   - existing review PASS, and reproducibility needs to be checked before sharing -> /repro-check
   - existing review PASS -> /research-experiment
   - existing experiment_res.md, but failure modes are still unclear -> /error-analysis
   - existing experiment_res.md plus figures -> /write-paper
   - existing paper/draft.md -> /artifact-review
   - existing figures with inconsistent captions or style -> /figure-standardize
   - preparing README.md or release-facing docs -> /release-layout after a fresh release gate exists
7. After the initial setup, tell the user the recommended next command and expected output files, then delete this file (BOOTSTRAP.md).

## Common Entry Paths

- I only have a research direction and no materials yet -> finish setup, then run /metabolism
- I already have a batch of papers -> run /research-survey
- I finished the survey but have not chosen a model route -> run /algorithm-selection
- I have a plan but the metric and evidence contract still feels unclear -> run /metric-audit
- I already have a plan and want to validate the data first -> run /dataset-validate
- I already have a plan and need a small, decisive ablation set -> run /ablation-planner
- I already have a plan and want honest baseline numbers first -> run /baseline-runner
- I already have several runs and want one clean registry -> run /experiment-tracker
- I already have implementation code -> run /research-review
- I already passed review and want to check reproducibility before sharing -> run /repro-check
- I already have experiment results but need structured failure analysis -> run /error-analysis
- I already have experiment results and figures -> run /write-paper
- I already have a draft that needs review -> run /artifact-review

## config.json Template

\`\`\`json
{
  "projectId": "${projectName}",
  "keywords": ["keyword-1", "keyword-2"],
  "arxivCategories": ["cs.LG"],
  "sources": ["arxiv", "openalex"],
  "currentDay": 0,
  "processed_ids": [],
  "createdAt": "${new Date().toISOString()}"
}
\`\`\`

> **Note:** Configure \`arxivCategories\` and \`sources\` based on the research domain.
> For natural science, social science, or other non-CS topics, it is fine to set \`arxivCategories\` to \`[]\` and rely primarily on OpenAlex.
`;
}

export function renderSoulMd(projectName: string): string {
  return `# Project Agent — ${projectName}

You are the research agent for project "${projectName}".

## Research Direction
{Filled during the BOOTSTRAP flow}

## Core Domain
Keywords: {Filled during the BOOTSTRAP flow}
arXiv Categories: {Filled during the BOOTSTRAP flow; leave empty if not applicable}
Literature Sources: {arXiv / OpenAlex / both}
`;
}

export function renderAgentsMd(): string {
  return `# Agent Operating Manual

## Workspace Layout

The agent workspace root is the project root (\`$W\`). All files are organized relative to \`$W\`:

\`\`\`
$W/
├── SOUL.md                      # identity and project direction
├── AGENTS.md                    # this document
├── config.json                  # project config (keywords, categories, current day)
├── progress_status.json         # agent-defined task progress for the current goal
│
├── papers/                      # literature artifacts
│   ├── {arxiv_id}/              # arXiv source files
│   └── {doi_slug}.pdf           # PDF files
│
├── knowledge/                   # persistent knowledge state
│   ├── _index.md                # global index
│   └── topic-*.md               # topic files (limit 50)
│
├── ideas/                       # hypotheses and research ideas
│   ├── hyp-*.md                 # generated hypotheses
│   └── selected_idea.md         # selected research idea
│
├── experiments/                 # experiment code and assets
│   ├── run.py                   # entry script
│   ├── requirements.txt
│   └── results/                 # experiment outputs
│
├── review/                      # review, audit, and writing outputs
├── paper/                       # experiment-driven paper outputs
│   ├── manuscript.tex           # top-level LaTeX entry
│   ├── build_paper.sh           # PDF build script
│   ├── references.bib           # bibliography placeholder
│   ├── sections/                # section-by-section TeX drafts
│   ├── figures/                 # paper-local figures
│   ├── assets/                  # supporting assets for paper generation
│   └── build/                   # PDF, logs, and build errors
│
├── log/                         # run logs
│   └── {YYYY-MM-DD}.md
│
└── skills/                      # workspace skills
\`\`\`

## Session Context

You may be activated in different session types:
- **Main session**: direct interaction with a human; can trigger orchestration skills such as \`research-pipeline\`
- **Cron session**: scheduled execution for recurring work such as daily metabolism
- **Spawn session**: dispatched by the main session (\`sessions_spawn\`) for one-off heavy tasks

Task instructions are injected when the session starts. Follow the injected instructions for that session.

## Conventions

### File Existence = Step Completion
Check whether the output file already exists before running a step. If it exists, skip it. This enables crash recovery and incremental progress.

### Immutability
Do not modify output files once written unless the user explicitly asks you to. Exception: \`project/\` may change during implement-review iteration.

### Progress Tracking
- Do not assume every project follows the same fixed stages.
- Define progress in \`progress_status.json\` based on the user's current goal.
- Update \`progress_status.json\` whenever the total task, current focus, subtask states, or next step changes.
- Recommended fields: \`overall_goal\`, \`current_focus\`, \`next_step\`, \`completed_tasks\`, \`total_tasks\`, \`subtasks\`.

### Knowledge File Rules
- Files under \`knowledge/\` are persistent knowledge state and must be edited carefully.
- Always read the current file before updating it.
- \`_index.md\` is the global index and must stay in sync with the topic files.
- Limit topic files to 50. Merge or archive low-activity topics when needed.

## Research Rigor

- Read the source material first, think second, answer third.
- Do not fabricate citations or experiment results. Every claim needs a source.
- Say "uncertain" when uncertain instead of guessing.
- Read the full paper source (\`.tex\`) when available; do not rely on the abstract alone.
- Ground ideas in real papers rather than unsupported intuition.

## Skill Outputs Summary

| Skill | Primary Outputs |
|-------|-----------------|
| /metabolism | Day 0: config.json, knowledge/ / Day 1+: papers/, knowledge/, ideas/hyp-*.md, log/ |
| /research-collect | papers/ |
| /research-survey | knowledge/, survey_res.md |
| /algorithm-selection | selection_res.md |
| /research-plan | plan_res.md |
| /metric-audit | metric_audit.md |
| /dataset-validate | data_validation.md |
| /ablation-planner | ablation_plan.md |
| /baseline-runner | baseline_res.md, experiments/baselines/ |
| /research-implement | experiments/ |
| /research-review | experiments/review/ |
| /repro-check | repro_check.md |
| /research-experiment | experiments/results/, experiment_res.md |
| /experiment-tracker | experiment_registry.md |
| /error-analysis | error_analysis.md |
| /idea-generation | ideas/ |
| /write-review-paper | review/ |
| /write-paper | paper/claim_inventory.md, paper/figures_manifest.md, paper/draft.md, paper/manuscript.tex, paper/build/manuscript.pdf |
| /artifact-review | review/artifact_review.md, review/release_checklist.md, review/release_gate.json |
| /figure-standardize | reports/figures/figure_spec.md or project/figures/figure_spec.md |
| /release-layout | README.md, docs/index.html, release-facing pages |

## Common ML Midstream Paths

- Survey exists but route choice is still unclear:
  - run \`/algorithm-selection\`
  - expected output: \`selection_res.md\`
- Plan exists and metric wording, baselines, or evidence layers need review:
  - run \`/metric-audit\`
  - expected output: \`metric_audit.md\`
- Plan exists and the project needs a dedicated data-quality check:
  - run \`/dataset-validate\`
  - expected output: \`data_validation.md\`
- Plan exists and the project needs a concise component-level ablation set:
  - run \`/ablation-planner\`
  - expected output: \`ablation_plan.md\`
- Plan exists and the project needs honest comparison numbers:
  - run \`/baseline-runner\`
  - expected outputs: \`baseline_res.md\`, optional baseline artifacts under \`experiments/baselines/\`
- Several runs already exist and the project needs a clean ledger:
  - run \`/experiment-tracker\`
  - expected output: \`experiment_registry.md\`
- Review already passed and the team needs reproducibility confidence before sharing:
  - run \`/repro-check\`
  - expected output: \`repro_check.md\`
- Experiment results exist but failure buckets are still unclear:
  - run \`/error-analysis\`
  - expected output: \`error_analysis.md\`

## Writing and Release Entry Points

Use these entry points when the project already has partial outputs and does not need to restart the full research pipeline:

- If you already have \`experiment_res.md\` and one or more result figures:
  - run \`/write-paper\`
  - expected outputs: \`paper/claim_inventory.md\`, \`paper/figures_manifest.md\`, \`paper/draft.md\`, \`paper/manuscript.tex\`, \`paper/build/manuscript.pdf\`
- If you already have \`paper/draft.md\` or another draft artifact that is about to be shared:
  - run \`/artifact-review\`
  - expected outputs: \`review/artifact_review.md\`, \`review/release_checklist.md\`, \`review/release_gate.json\`
- If you already have figures but their style, captioning, units, or evidence labels are inconsistent:
  - run \`/figure-standardize\`
  - expected outputs: figure specs, caption updates, and standardized release-facing figures
- If you are preparing a \`README.md\` or release-facing page for sharing:
  - run \`/release-layout\`
  - expected outputs: README updates, docs landing-page updates, and clearer release entry surfaces
  - do this only after \`/artifact-review\` has produced a fresh release gate for the current artifacts
`;
}
