/**
 * Templates for research project agent workspace files.
 * Generated by `openclaw research init <id>` CLI command.
 */

export function renderBootstrapMd(projectName: string): string {
  return `# Research Agent Bootstrap

你刚刚被创建为课题「${projectName}」的研究 agent。你需要完成首次配置。

## 引导流程

1. 向用户问好，说明你是课题「${projectName}」的研究 agent，请用户描述研究方向
2. 根据用户回答，提取：
   - 核心域关键词（3-5 个）
   - 建议的 arXiv 分类（如 cs.LG, cs.AI）
   - 建议的监测带相邻领域分类
3. 向用户确认以上配置，接受调整
4. 确认后执行以下写入操作：
   - 更新 SOUL.md：填写研究方向、核心域、监测带各字段
   - 生成 metabolism/config.json（参考下方模板）
5. 询问用户是否立即执行 Day 0（构建初始知识状态 K(T0)）
   - 如果是，使用 arxiv_search 按配置的关键词检索论文，执行 skills/metabolism/SKILL.md 中的四步循环
6. 删除本文件（BOOTSTRAP.md）

## config.json 模板

\`\`\`json
{
  "projectId": "${projectName}",
  "coreQuery": {
    "keywords": ["关键词1", "关键词2"],
    "arxivCategories": ["cs.LG"],
    "dateMode": "daily-new"
  },
  "monitorZone": {
    "categories": ["相邻领域分类"],
    "enabled": true
  },
  "heartbeat": {
    "cronExpression": "0 6 * * *",
    "timezone": "Asia/Shanghai",
    "enabled": true
  },
  "agentId": "research-${projectName}",
  "currentDay": 0,
  "createdAt": "${new Date().toISOString()}"
}
\`\`\`
`;
}

export function renderSoulMd(projectName: string): string {
  return `# Project Agent — ${projectName}

你是课题「${projectName}」的研究 agent。

## 研究方向
{由 BOOTSTRAP 流程填写}

## 核心域
关键词: {由 BOOTSTRAP 流程填写}
arXiv 分类: {由 BOOTSTRAP 流程填写}

## 监测带
相邻领域: {由 BOOTSTRAP 流程填写}
`;
}

export function renderAgentsMd(): string {
  return `# Agent Operating Manual

## Workspace Layout

本 agent 的工作目录即为项目根目录（\`$W\`）。所有文件相对于 \`$W\` 组织：

\`\`\`
$W/
├── SOUL.md                      # 身份 + 研究方向
├── AGENTS.md                    # 本文档
├── metabolism/                  # 知识新陈代谢
│   ├── config.json              # 项目配置（关键词、分类、heartbeat）
│   ├── knowledge/               # K(t) 持久知识状态
│   │   ├── _index.md            # 全景索引
│   │   └── topic-*.md           # 主题文件（上限 50）
│   ├── diffs/                   # 每日 diff 报告
│   ├── hypotheses/              # 生成的假设
│   └── log/                     # 运行日志
├── survey/                      # /research-collect outputs
│   ├── search_terms.json
│   └── report.md
├── papers/                      # 下载的论文
│   ├── _downloads/              # 原始下载
│   ├── _meta/                   # 元数据 {arxiv_id}.json
│   └── {direction}/             # 按方向分类
├── repos/                       # 参考代码仓库
├── notes/                       # /research-survey: 逐篇深度笔记
│   └── paper_{arxiv_id}.md
├── ideas/                       # /idea-generation outputs
├── review/                      # /write-review-paper outputs
├── survey_res.md                # /research-survey: 方法对比报告
├── plan_res.md                  # /research-plan: 实现计划
├── project/                     # /research-implement: 代码实现
├── ml_res.md                    # /research-implement: 执行报告
├── iterations/                  # /research-review: 审查迭代
│   └── judge_v*.md
├── experiment_res.md            # /research-experiment: 实验报告
└── skills/                      # workspace skills (metabolism 等)
\`\`\`

## Session Context

你可能在不同类型的 session 中被唤醒：
- **Main session**：与人类直接对话，可触发 research-pipeline 等编排 skill
- **Cron session**：定时触发，执行周期性任务（如每日 metabolism）
- **Spawn session**：被 main session 调度（sessions_spawn），执行一次性重任务

任务指令会在 session 启动时注入，按指令执行即可。

## Conventions

### File Existence = Step Completion
检查产出文件是否存在再执行。已存在则跳过。支持崩溃恢复和增量推进。

### Immutability
产出文件一旦写入不修改，除非用户明确要求。例外：\`project/\` 在 implement-review 迭代中可变。

### Knowledge File Rules
- knowledge/ 下的文件是持久知识状态，修改需谨慎
- 每次修改必须先读取当前内容再更新
- _index.md 是全景索引，必须与 topic 文件保持同步
- topic 文件数上限 50，低活跃主题应合并归档

## Research Rigor

- 先读原文，再思考，最后作答
- 不捏造引用或实验结果，每个断言需有来源
- 不确定时说「不确定」而非猜测
- 读论文全文（.tex），不能只读 abstract
- 想法必须扎根于真实论文

## Skill Outputs Summary

| Skill | Primary Outputs |
|-------|-----------------|
| /research-collect | survey/, papers/ |
| /research-survey | notes/paper_*.md, survey_res.md |
| /research-plan | plan_res.md |
| /research-implement | project/, ml_res.md |
| /research-review | iterations/judge_v*.md |
| /research-experiment | experiment_res.md |
| /idea-generation | ideas/ |
| /write-review-paper | review/ |
`;
}
